### ISSUE TITLE
Create .exe with build

### ISSUE THREAD

**Issue by rtulip** [rtulip/rustGame#119]

**Comment by rtulip** [comment]
I'll need to test on windows, but it seems as if an executable is found under target/debug. I'll need to look into this further, but this might be handled for me.

**Comment by rtulip** [comment]
If @mroesli, you can test if this works on windows, that would be great.

**Comment by mroesli** [comment]
According to the rust book documentation [here](https://doc.rust-lang.org/book/ch01-03-hello-cargo.html#building-and-running-a-cargo-project), it automatically creates the exe on builds. I also built the project on my machine and was able to run the exe successfully, so it is good to go! :+1: 
One thing you may want to consider is have it show up as part of your [release patches](https://github.com/rtulip/rustGame/releases) or have an exe that builds and then runs the game.

**Comment by rtulip** [comment]
Ok v0.3.0 has a .exe in the release. I'll need to figure out how to do this better in the future, but at least for now there's something. I'll need to try on windows, but at least on Linux, you need to manually set the file as an executable.

**Comment by rtulip** [comment]
Ok confirmed it doesn't work on windows. This'll be something I look into again in the future
