### ISSUE TITLE
Add reviewing requirements

### ISSUE THREAD

**Issue by mroesli** [rtulip/rustGame#51]
Need to consider adding reviewing requirements when doing pull requests in the settings. 

A good tutorial on this is this [Github lab](https://lab.github.com/githubtraining/reviewing-pull-requests).

**Comment by mroesli** [comment]
Another good couple labs:

- [securing your workflows](https://lab.github.com/githubtraining/securing-your-workflows)
- [create a release base workflow](https://lab.github.com/githubtraining/create-a-release-based-workflow)

I might go through them as well considering they have recently updated both of them.

**Comment by rtulip** [comment]
I'll give this a look for sure

**Comment by rtulip** [comment]
Considering it's mostly me working on things right now, I'm going to leave this be for v0.3.0, but I can create some reviewing requirements if anyone's interested in working on this.
